# Generated by Django 2.1.7 on 2019-03-02 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_name', models.CharField(max_length=200)),
                ('cast_resume', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='image')),
                ('payback_time', models.DurationField()),
                ('country', models.CharField(max_length=200)),
                ('release', models.DateTimeField(verbose_name='date published')),
                ('award', models.CharField(max_length=200)),
                ('cast', models.ManyToManyField(to='Oort.Cast')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=200)),
                ('director_resume', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_text', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='contents',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oort.Director'),
        ),
        migrations.AddField(
            model_name='contents',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oort.Genre'),
        ),
    ]
