# Generated by Django 2.1.7 on 2019-03-02 06:49

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('Oort', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contents',
            new_name='Content',
        ),
    ]
