# Generated by Django 2.1.7 on 2019-03-02 07:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Oort', '0002_auto_20190302_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='cast_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='content_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='director_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='genre_text',
            new_name='genre',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='cast_resume',
        ),
        migrations.RemoveField(
            model_name='director',
            name='director_resume',
        ),
        migrations.AddField(
            model_name='cast',
            name='resume',
            field=models.TextField(default='Dummy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='resume',
            field=models.TextField(default='dummy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='release',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 2, 7, 53, 43, 92887, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='content',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 2, 7, 53, 43, 91918, tzinfo=utc)),
        ),
    ]
