# Generated by Django 2.1.7 on 2019-03-02 08:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Oort', '0003_auto_20190302_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='content',
            name='release',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 2, 8, 15, 27, 11757, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='genre',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 2, 8, 15, 27, 10758, tzinfo=utc)),
        ),
    ]
