# Generated by Django 2.1.7 on 2019-03-06 11:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Oort', '0004_auto_20190302_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='release',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 6, 11, 28, 14, 399952, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='content',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 6, 11, 28, 14, 399952, tzinfo=utc)),
        ),
    ]
