# Generated by Django 2.1.7 on 2019-03-21 08:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Oort', '0005_auto_20190306_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='award',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='cast',
            field=models.ManyToManyField(blank=True, null=True, to='Oort.Cast'),
        ),
        migrations.AlterField(
            model_name='content',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Oort.Director'),
        ),
        migrations.AlterField(
            model_name='content',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Oort.Genre'),
        ),
        migrations.AlterField(
            model_name='content',
            name='payback_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='release',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 21, 8, 55, 3, 648394, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 8, 55, 3, 648394, tzinfo=utc)),
        ),
    ]
